name: 01 Create Base

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          mkdir -p app/src/main/java/com/robot/mrkeyboard
          mkdir -p app/src/main/res/{xml,values,drawable}

          echo 'rootProject.name="MrRobotKeyboard"' > settings.gradle

          cat > build.gradle <<EOF
plugins {
    id "com.android.application" version "8.5.2" apply false
    id "org.jetbrains.kotlin.android" version "1.9.24" apply false
}
EOF

      - run: |
          git config user.name bot
          git config user.email bot@github.com
          git add .
          git commit -m "Base created" || echo done
          git push
