name: 02 Android Config

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cat > app/build.gradle <<EOF
plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "com.robot.mrkeyboard"
    compileSdk 35

    defaultConfig {
        applicationId "com.robot.mrkeyboard"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}
EOF

      - run: |
          git add .
          git commit -m "Android config" || echo done
          git push
